version: '3.8'
name: collectihub

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: cards_test
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
