name: collectihub

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: cards_test
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    profiles:
      - testing
      - development

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    profiles:
      - testing

volumes:
  dbdata:
