# https://taskfile.dev

version: "3"

tasks:
  swag-rebuild:
    cmds:
      - swag fmt
      - swag init -g cmd/api/main.go
    silent: false
  run:
    cmds:
      - go run ./cmd/api/
    silent: false
  test:
    cmds:
      - go test -v ./... -cover
    silent: false
